### ISSUE TITLE
Please add plugin properties to configuration validator

### ISSUE THREAD

**Issue by maplion** [davidgf/serverless-plugin-canary-deployments#102]
(Thanks for reporting an issue! Please, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. install serverless 2.14
2. add serverless-plugin-canary-deployments as a plugin to your serverless.yml
3. make a deployment

What happens?
-------------
There is a configuration validation warning

What were you expecting to happen?
----------------------------------
No warning for something that is part of the plugin

Any logs, error output, etc?
----------------------------
Serverless: Configuration warning:
Serverless:   at 'functions['hosting-api']': unrecognized property 'deploymentSettings'
Serverless:   at 'functions['hosting-data-sync-handler']': unrecognized property 'deploymentSettings'
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation

Any other comments?
-------------------
Can you have this plugin's attribute additions added to the configuration-validator?

What versions of software are you using?
----------------------------------------
    "serverless": "^2.14.0",
    "serverless-plugin-canary-deployments": "^0.4.8"

**Comment by sudo-shubham** [comment]
+1

**Comment by kdybicz** [comment]
This still seems to be an issue for me:
```
Serverless: Configuration warning at 'functions.graphql': unrecognized property 'deploymentSettings'
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Deprecation warning: Starting with next major, Serverless will throw on configuration errors by default. Adapt to this behavior now by adding "configValidationMode: error" to service configuration
            More Info: https://www.serverless.com/framework/docs/deprecations/#CONFIG_VALIDATION_MODE_DEFAULT
```

My config:
```
"serverless": "^2.12.0",
"serverless-plugin-canary-deployments": "^0.5.0",
```

**Comment by Nyholm** [comment]
PR #113 is not released yet. Try it out with: 

```
 npm install davidgf/serverless-plugin-canary-deployments#master --save-dev 
```

-------

I can confirm that #113 is working.
