### ISSUE TITLE
0.5.0 - Circular dependency created and deploy fails

### ISSUE THREAD

**Issue by WWalshC4** [davidgf/serverless-plugin-canary-deployments#114]
Last week, I had a working deployment using blue/green with postHook and preHook tests.  Deploying the same code since 0.5.0 was released for serverless-plugin-canary-deployments results in a CloudFormation error

What are the steps to reproduce this issue?
-------------------------------------------
1. … Deploy a previously working serverless install using 0.5.0 plugin version

What happens?
-------------
Serverless: Validating template...
 
  Error -------------------------------------------------- Error: The CloudFormation template is invalid: Circular dependency between resources: [<snipped resource list>]
      at /usr/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:20:13
      at runNextTicks (internal/process/task_queues.js:58:5)
      at processImmediate (internal/timers.js:434:9)

What were you expecting to happen?
----------------------------------
Blue/Green deploy on AWS

Can currently solve by installing the 0.4.8 plugin, but thought it worth flagging here.

**Comment by davidgf** [comment]
Hi @WWalshC4, thanks for reporting this issue. Unfortunately, even though the error message states that there's a circular dependency between resources, it doesn't say which ones in particular are affected. Is there any chance you could possibly figure out which specific resources are causing the issue?

**Comment by WWalshC4** [comment]
The same serverless yml config deploys with no issues when using plugin-canary 0.4.8.  I can't see any obvious circular dependencies, and tried commenting out any refs that looked suspicious.
________________________________

**Comment by davidgf** [comment]
The last release included a new feature that could affect hooks. Could you install the plugin from a branch where I removed specifically that functionality and see if that resolves the issue? You can do that by executing `npm i davidgf/serverless-plugin-canary-deployments#revert-110-execution-role-code-deploy-hook-permissions`. It would be a huge help, thanks in advance

**Comment by WWalshC4** [comment]
Confirm that using that version solved the issue.  Deploy proceeded as expected, and logs indicate that was the version used.

**Comment by davidgf** [comment]
Thanks a lot for your help! @72636c it seems that for some reason #110 is causing some deployments to fail, any chance you could look into this?

**Comment by 72636c** [comment]
@WWalshC4 would you be able to share a cut down version of your `serverless.yml`?

**Comment by WWalshC4** [comment]
Sure thing, have attached them here.

[serverless.zip](https://github.com/davidgf/serverless-plugin-canary-deployments/files/5981297/serverless.zip)

**Comment by WWalshC4** [comment]
Is there anything else you need to work on this?

**Comment by 72636c** [comment]
@WWalshC4 real sorry for the delay here, I've been swamped 😞. I'll try to take a look this week, please ping here again if I haven't gotten back to you!

**Comment by WWalshC4** [comment]
I see that a new release (0.6.0) has gone out, and this fix wasn't included.  This is now a problem as the change that happened at AWS to change the IAM role for Lamba Full Access has now happened; I can't use the older version that didn't have this bug because that older version doesn't have the right role specified.

**Comment by rfaasicreative** [comment]
@72636c I also want to confirm this bug still exists for release 0.6.0. It only occurs when the postTrafficHook/preTrafficHook and the alarm are configured. The deployment of the example folder also results in the error message.

**Comment by samchungy** [comment]
Heyo @72636c and @davidgf I found the reason for the circular dependency.

```
E3004 Circular Dependencies for resource IamRoleLambdaExecution. Circular dependency with [HelloLambdaFunctionDeploymentGroup]
.serverless/cloudformation-template-update-stack.json:92:5

E3004 Circular Dependencies for resource HelloLambdaFunction. Circular dependency with [IamRoleLambdaExecution]
.serverless/cloudformation-template-update-stack.json:189:5

E3004 Circular Dependencies for resource HelloFooAlarm. Circular dependency with [HelloLambdaFunction]
.serverless/cloudformation-template-update-stack.json:406:5

E3004 Circular Dependencies for resource HelloLambdaFunctionDeploymentGroup. Circular dependency with [HelloFooAlarm]
.serverless/cloudformation-template-update-stack.json:468:5
```
cfn-lint pulled this up.

We can solve this by setting the set deployment group name and referring to it in the IAM role with a string template instead of !Sub.

 I'm happy to raise a PR if we can agree on a pattern for the name generation. The current pattern for autogeneration within AWS appears to be `${stackName}-${physicalId}-${randomId}` sls-canary-example-dev-HelloLambdaFunctionDeploymentGroup-EOZXA7LB7QCL but I think `${stackName}-${physicalId}` should be sufficient for a name?
