### ISSUE TITLE
aws:policy/AWSLambdaFullAccess does not exist or is not attachable

### ISSUE THREAD

**Issue by jastsai** [davidgf/serverless-plugin-canary-deployments#117]
(Thanks for reporting an issue! Please, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
sls deploy

What happens?
-------------
[11:19:22][Step 1/3]  Serverless Error ----------------------------------------
[11:19:22][Step 1/3]  
[11:19:22][Step 1/3]   An error occurred: CodeDeployServiceRole - Policy arn:aws:iam::aws:policy/AWSLambdaFullAccess does not exist or is not attachable. (Service: AmazonIdentityManagement; Status Code: 404; Error Code: NoSuchEntity; Request ID: a40989a6-a677-41a1-88db-c0c455317843; Proxy: null).
[11:19:22][Step 1/3] 
…
(After March 1, 2021, the AWS managed policies AWSLambdaReadOnlyAccess and AWSLambdaFullAccess will be deprecated and can no longer be attached to new IAM users. For more information about policy deprecations, see Deprecated AWS managed policies in the IAM User Guide.)
https://docs.aws.amazon.com/lambda/latest/dg/security_iam_troubleshoot.html#security_iam_troubleshoot-admin-deprecation

The AWSLambdaFullAccess is being used in the current release.
check here
https://github.com/davidgf/serverless-plugin-canary-deployments/search?q=AWSLambdaFullAccess

What were you expecting to happen?
----------------------------------

…

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://pastebin.com/ and insert the link here.)

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
v0.5.0

**Comment by davidgf** [comment]
Fixed by #116
