### ISSUE TITLE
Release 0.5.1

### ISSUE THREAD

**Issue by Nyholm** [davidgf/serverless-plugin-canary-deployments#118]
Could I kindly ask for a 0.5.1 release?

I would like to use https://github.com/davidgf/serverless-plugin-canary-deployments/pull/113

I'm currently using the master branch of this package in my applications.

**Comment by davidgf** [comment]
Done, apologies for the delay

**Comment by Nyholm** [comment]
Wow. You are the best. 

Thank you!
