### ISSUE TITLE
Doesn't see latest release version in the "release" section

### ISSUE THREAD

**Issue by jastsai** [davidgf/serverless-plugin-canary-deployments#120]
(Thanks for reporting an issue! Please, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Go to https://github.com/davidgf/serverless-plugin-canary-deployments/releases

What happens?
-------------
Does not see versions newer than 0.5.0

What were you expecting to happen?
----------------------------------
at least see 0.6.0 ?

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://pastebin.com/ and insert the link here.)

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------

**Comment by davidgf** [comment]
Thanks for spotting this one! I honestly forgot to create the GH release, although `v0.6.0` has been available on npm since a week ago
