### ISSUE TITLE
How can I only invoke the canary version of my lambda

### ISSUE THREAD

**Issue by chaoyangnz** [davidgf/serverless-plugin-canary-deployments#123]
I'd like to do a post production testing once a canary version is deployed.
So i added a postTraffic hook, but how can i specify the version to invoke the newly deployed lambda only?

**Comment by davidgf** [comment]
The `event` being passed in to the hook function might have some information about which versions it's shifting traffic to, but I couldn't find any sample in the docs. In case it doesn't, you can always use [the AWS SDK to get the list of aliases](https://docs.aws.amazon.com/lambda/latest/dg/API_ListAliases.html) and pick the last one.
