### ISSUE TITLE
how can I stop deleting the preTraffic lambda (include its logs group) and CodeDeploy deployment

### ISSUE THREAD

**Issue by chaoyangnz** [davidgf/serverless-plugin-canary-deployments#125]
That makes trouble-shooting really hard if I cannot quickly check the logs to find the problem, because the preTraffic lambda and its log group will be deleted whenever the deployment succeeds or cancelled.

CodeDeploy application and deployment are deleted as well.

How can I stop the behaviour?

**Comment by chaoyangnz** [comment]
not an issue any longer

**Comment by skyzenr** [comment]
Hi @chaoyangnz , same issue on our side. How did you solve that ? Thanks
