### ISSUE TITLE
AWS::CodeDeploy::DeploymentGroup not generated if only global `deploymentSettings` are defined

### ISSUE THREAD

**Issue by aburkhalter512** [davidgf/serverless-plugin-canary-deployments#145]
What are the steps to reproduce this issue?
-------------------------------------------
1. Omit `deploymentSettings` from all lambdas
2. Add `deploymentSettings` to the top level custom field e.g.
```
custom:
  deploymentSettings:
    type: 'AllAtOnce'
    alias: live
```
3. Run `sls package`

What happens?
-------------
No `AWS::CodeDeploy::DeploymentGroup` resources are generated for any lambdas included in the serverless definitions. If you add an empty `deploymentSettings:` field to any lambda, the global settings get applied to all lambdas.

What were you expecting to happen?
----------------------------------
I expect that all lambdas default to the global settings, regardless if any lambda defines `deploymentSettings` specific to that lambda

Any logs, error output, etc?
----------------------------
N/A

Any other comments?
-------------------
This looks like a bug specifically with this function: https://github.com/davidgf/serverless-plugin-canary-deployments/blob/5053d2f9e9d16715a687dc300745c892d1b9af78/serverless-plugin-canary-deployments.js#L86
```
  shouldDeployDeployGradually () {
    return this.withDeploymentPreferencesFns.length > 0 && this.currentStageEnabled()
  }
```
I'm guessing the function should also check to see if any global deployment settings are defined.

What versions of software are you using?
----------------------------------------
0.7.0

**Comment by davidgf** [comment]
This is not a bug, but a feature :smile: The top level setting is not meant to be applied globally, but only on those functions where deployment settings are defined, providing some default values for them. Deployments is a sensitive operation, and in my opinion it's better to explicitly define this kind of settings for each function to be fully aware of which functions are going to be deployed gradually and which ones are not. In any case, I understand that this is confusing some people, feel free to fork the plugin and adapt it to your preferences. If memory serves, there's even a closed PR that implemented the feature you're describing
