### ISSUE TITLE
Default values not working?

### ISSUE THREAD

**Issue by josephjohansson** [davidgf/serverless-plugin-canary-deployments#31]
Hi. Thanks for this plugin cant be overstated how useful it is. I am having trouble defining and global alias and type. I have the following setup but it does not create the code deploy applications. When I place the deploymentSettings inside each function however it works perfectly. If this is not the current use case I think it should be an option and if its not desired behavior I think the documentation should be updated to be more clear since it implies that the setup below should work.

```service: users

provider:
  name: aws
  runtime: python3.6
  region: us-west-2
  endpointType: regional
  managedPolicyArns:
    - "arn:aws:iam::aws:policy/service-role/AWSCodeDeployRoleForLambda"


plugins:
  - serverless-attach-managed-policy
  - serverless-plugin-canary-deployments

custom:
  deploymentSettings:
    type: Canary10Percent30Minutes
    alias: Production
    stages:
      - prod

  stage: ${opt:stage}


functions:
  someFunc:
    handler: someFunc.someFunc
    runtime: python3.6
    events:
      - http:
          path: someFunc
          method: POST
          cors: true
          authorizer:
            arn: ${self:custom.cognitoArn}```

**Comment by davidgf** [comment]
Hey @rodrigjg, thanks a lot for your feedback! You nailed it, it's lack of documentation, the current implementation simply takes the settings defined under `custom` as defaults for those functions where `deploymentSettings` is defined. One use case of this would be when you have like 10 functions that you want to deploy gradually and want to use the same alias, so you could just define it in the global settings and skip it in the functions' section. I didn't want the global settings to imply that all the functions are deployed gradually, as you might not want that while you'd like to define some defaults. So, besides a more accurate documentation, probably adding a new config to apply the global settings to all functions (hence deploy them all gradually) would totally make sense. If you want to give it a shot, contributions are welcome :)

**Comment by rodrigjg** [comment]
Hey @davidgf sorry for the late response I'll work on PR in the coming weeks for this. Sorry I could not reply I was on vacation! I will probably fix the documentation first and then move on to the global setting. Thanks.

**Comment by exoego** [comment]
I believe #53 closes this issue without breaking change.
