### ISSUE TITLE
Does this lib supports nodejsV8 and AllAtOnce mode for lambda deployment?

### ISSUE THREAD

**Issue by AlexSun98** [davidgf/serverless-plugin-canary-deployments#33]
Does this lib supports nodejsV8 and AllAtOnce mode for lambda deployment?

**Comment by davidgf** [comment]
Yes, it supports all the deployment modes listed [here](https://docs.aws.amazon.com/lambda/latest/dg/automating-updates-to-serverless-apps.html)
