### ISSUE TITLE
Calling lambda from pre hook

### ISSUE THREAD

**Issue by orjan** [davidgf/serverless-plugin-canary-deployments#34]
Hi and thanks for an awesome plugin!

Is there a way to get hold of a reference to the new lambda so it can be called and verified from the pre hook? Like `NewVersion` is being passed in [implementing-safe-aws-lambda-deployments-with-aws-codedeploy](https://aws.amazon.com/blogs/compute/implementing-safe-aws-lambda-deployments-with-aws-codedeploy/)

**Comment by davidgf** [comment]
Hey @orjan, thanks a lot for reaching out! I guess the question would be if you can figure out the Lambda Version resource logical name in `serverless.yml`, which I'm not sure it's possible. Taking a look [at their docs](https://serverless.com/framework/docs/providers/aws/guide/resources/), the version logical ID looks like this `{normalizedFunctionName}LambdaVersion{sha256}`, you could probably ask Serverless maintainers if you can somehow get the sha256 of a function in `serverless.yml`.
That said, you probably don't need the function version to execute the new code, you can simply invoke `$Latest`, which should match with the new version when you execute the pre hook.
