### ISSUE TITLE
canary 100% of traffic for testing

### ISSUE THREAD

**Issue by lolcookie** [davidgf/serverless-plugin-canary-deployments#36]
I would like to run tests against the canary env when deployed so I assume the easiest way to do this is to transfer 100% of the traffic over for testing, is this possible?

**Comment by davidgf** [comment]
Yes, you can do so by setting the `deploymentSettings` `type` to `AllAtOnce`. Anyway, if you're going to invoke the Lambda function directly (not through an event trigger) to perform your tests, you can just execute the `$Latest` version, since it's gonna match the latest release.
