### ISSUE TITLE
Scheduled Lambda Events not triggering when used with this plugin

### ISSUE THREAD

**Issue by DipinShetty** [davidgf/serverless-plugin-canary-deployments#48]
We found that when we have a lambda function which is scheduled through a cloud watch event rule of every x minutes. the lambda fails to trigger and we see a specific error as shown below and it needs to be fixed manually in the AWS console

<img width="1769" alt="screenshot 2019-02-07 at 8 12 48 pm" src="https://user-images.githubusercontent.com/20219220/52419067-5ad92a80-2b15-11e9-8a27-f6bc75930048.png">

serverless.yml code:

Sample function:
    handler: src/index.js
    description: refresh tokens
    events:
      - schedule: rate(5 minutes)
    deploymentSettings:
      type: AllAtOnce #Canary10Percent5Minutes, Linear10PercentEvery1Minute, AllAtOnce
      alias: Live
      preTrafficHook: preHook
      postTrafficHook: postHook

**Comment by michael-murphree** [comment]
It seems that on deployment, the trigger is not correctly pointed to the new production alias for the function.

**Comment by davidgf** [comment]
@DipinShetty I've just tried the CW Scheduled events integration and seems to be working properly
