### ISSUE TITLE
SQS events

### ISSUE THREAD

**Issue by lielran** [davidgf/serverless-plugin-canary-deployments#56]
I'm mostly using SQS events. using code deploy seems to work by traffic shifting events to new lambdas. 

in the readme it seems that this plugin doesn't support it. am I missing something? what should be added in order to support it?

**Comment by lielran** [comment]
I think I spotted what is not working with SQS events, it seems that the new version that should get 10% first for X min is not registered/update the subscription to the SNS. after code-deploy deployment, I see a drop-down in the invocations.

**Comment by davidgf** [comment]
Hey @lielran, sorry for the delay. Even though the docs don't explicitly say the plugin works with SQS based events, it actually does, as they're stream based events (such as Kinesis' or DynamoDB's). I'll update the README to reflect this.

**Comment by lielran** [comment]
Can you explain how it works? Like both blue and green are still fetching
messages...
How can you do traffic shifting like that?

**Comment by davidgf** [comment]
Both the previous and the new version get executed at the same time during the deployment. The percentage of traffic the new function gets and how it's shifted pretty much depends on the deployment `type` you configure. You can see the deployment types at your disposal in the [README](https://github.com/davidgf/serverless-plugin-canary-deployments#configuration) and in the [AWS CodeDeploy docs](https://docs.aws.amazon.com/codedeploy/latest/userguide/deployment-configurations.html)
