### ISSUE TITLE
[Question] Non-Lambda resources support - SQS, SNS 

### ISSUE THREAD

**Issue by dcworldwide** [davidgf/serverless-plugin-canary-deployments#62]
Nice work,

So If my serverless configuration included a number of SNS, SQS, Lambda resources, would each of these resources be deployed with a new version as new resources, fully isolated from the previous version? 

If yes, is the deploy atomic? I.e. if there are any errors, will the entire deploy rollback?

**Comment by davidgf** [comment]
No, the plugin just allows you gradually deploying new Lambda function versions, which doesn't affect your infrastructure. As an example, let's say that you have a Lambda function that reads from a DynamoDB table. If you deploy your function using this plugin, its last two versions will be running in parallel and the traffic will be gradually shifted to the new version according to your settings, but the DynamoDB table both versions are using is exactly the same one.

**Comment by dcworldwide** [comment]
Ok thanks, I understand the scope of this lib now.

Are you saying that there is no need to version sqs or sns resources?

**Comment by davidgf** [comment]
Exactly. If you're interested in how this works under the hood, you can take a look at a [blog post](https://medium.com/hackernoon/canary-deployments-in-serverless-applications-b0f47fa9b409) I wrote a while ago, which gives you an overview of the underlying technology used by the plugin.
