### ISSUE TITLE
Lambda doesn't deploy gradually when alarm is specified

### ISSUE THREAD

**Issue by FoleyTim** [davidgf/serverless-plugin-canary-deployments#65]
1. I use this YML

> ```
> 
> service: url
> 
> plugins:
>   - serverless-offline
>   - serverless-pseudo-parameters
>   - serverless-plugin-stage-variables
>   - serverless-plugin-tracing
>   - serverless-plugin-canary-deployments
> 
> package:
>   # include:
>   #   - handlers
>   exclude:
>     - .gitignore
>     - test-data*.json
>     - doc
>     - scripts
>     - aws-sdk
>     - .bak
>     - .local*
>     - config/config.local.json
>     # - .serverless  
> 
> ApiGatewayStage:
>   Type: AWS::ApiGateway::Stage
>   Properties:
>     RestApiId:
>       Ref: ApiGatewayRestApi
>     MethodSettings:
>     - DataTraceEnabled: true
>       HttpMethod: "*"
>       LoggingLevel: INFO
>       ResourcePath: "/*"
>       MetricsEnabled: true
> 
> resources:
>   Resources:
>     urlLogGroup:
>       Type: AWS::Logs::LogGroup
>       Properties:
>         RetentionInDays: "14"
> 
> custom: 
>   configS3: config-sys-${opt:stage, 'dev'}
>   configS3Path: url
>   deploymentSettings: //have tried with and without this in custom
>     type: Linear10PercentEvery1Minute
>     alias: fivehundred
>     alarms:
>       - name: Canary test alarm
>       
> provider:
>   name: aws
>   timeout: 300
>   runtime: nodejs8.10
>   stage: ${opt:stage, 'dev'}
>   region: ap-southeast-2
>   tracing: true
>   endpointType: regional
> 
>   environment:
>     region: ${self:provider.region}
>     stage: ${opt:stage, 'dev'}
>     configBucket: ${self:custom.configS3}
>     configPath: ${self:custom.configS3Path}
> 
>   deploymentBucket:
>     name: name-deploy-${opt:stage, 'dev'}
> 
>   iamRoleStatements:
>     - Effect: Allow
>       Action:
>         - codedeploy:*
>       Resource:
>         - "*"
>     - Effect: "Allow" 
>       Action:
>         - "xray:PutTraceSegments"
>         - "xray:PutTelemetryRecords"
>       Resource: 
>         - "*" 
>     - Effect: "Allow"
>       Action:
>         - sns:publish
>       Resource: "arn:aws:sns:${opt:region, self:provider.region}:#{AWS::AccountId}:error-sns-${opt:stage, 'dev'}"
>     - Effect: Allow
>       Action:
>         - "s3:ListBucket"
>         - "s3:GetObject"
>       Resource: "arn:aws:s3:::${self:custom.configS3}/${self:custom.configS3Path}/*"
> 
> functions:
>   getUrl:
>     handler: handler.getUrl
>     timeout: 300
>     events:
>       - http: 
>           path: /url
>           method: post
>           cors:
>             origin: '*'
>             headers:
>             - Content-Type
>             - X-Amz-Date
>             - Authorization
>             - X-Api-Key
>             - X-Amz-Security-Token
>             - X-Amz-User-Agent
>             - Access-Control-Allow-Origin
>             - Access-Control-Allow-Credentials
>             allowCredentials: true
>           private: true
>     deploymentSettings:
>       type: Linear10PercentEvery1Minute
>       alias: fivehundred
>       alarms:
>         - name: Canary test alarm
>     onError: arn:aws:sns:${opt:region, self:provider.region}:#{AWS::AccountId}:error-sns-${opt:stage, 'dev'}
> ```

2.
if I SLS deploy with this in the yml:

>     deploymentSettings:
>       type: Linear10PercentEvery1Minute
>       alias: fivehundred
> 

everything works as expected.
But when I specify alarm:

>     deploymentSettings:
>       type: Linear10PercentEvery1Minute
>       alias: fivehundred
>       alarms:
>         - name: Canary test alarm

The deployment happens instantly.

What was I expecting to happen:
I am expecting the lambda to deploy with the traffic shifting gradually over 10 minutes, as it does when i don't specify an alarm.

Any logs, error output, etc?
No errors in console, seems to deploy as normal

Any other comments?
I then deployed the lambda again with all deployment settings commented out and I got an error in console saying that the deployment had been rolled back because the alarm was triggered.

What versions of software are you using?
----------------------------------------
    "serverless-plugin-canary-deployments": "^0.4.8",
    "serverless-offline": "^5.8.0",

I have confirmed I am using the right alarm name 
![image](https://user-images.githubusercontent.com/18388635/62504719-e249f100-b84d-11e9-976f-64db681720f2.png)

some other stuff I noticed:
This only happens the first time you deploy with an alarm specified. If I deploy my lambda with the above yml, it will instantly change to the new version. But if I change the code (not yml) slightly and redeploy it seems to work.  however if I make changes to the deployment settings in the yml in between deployments it will deploy instantly both times.

**Comment by davidgf** [comment]
Hi there! Deploying functions gradually only when there's a code change is expected, as no new version would be created otherwise. Regarding the alarm issue, have you tried creating it in the same serverless.yml file (or rather, the same CloudFormation stack)? You can see an example of that [here](https://github.com/davidgf/serverless-plugin-canary-deployments/blob/master/example/serverless.yml), leveraging the `serverless-plugin-aws-alerts`. Also, seeing the resulting CloudFormation template would be helpful.

**Comment by FoleyTim** [comment]
Hey David, thanks for getting back to me. 

> Deploying functions gradually only when there's a code change is expected, as no new version would be created otherwise.
I am making a code change everytime I deploy. I am trying to test this plug in so I made a lambda that returns a Letter and I change that letter each time I deploy.
I will give your alarm recommendation a go.
Thanks
Tim
