### ISSUE TITLE
How to perform integration test in preHook

### ISSUE THREAD

**Issue by shaheer-k** [davidgf/serverless-plugin-canary-deployments#70]
Hi

I have successfully enabled the canary deployment plugin in our serverless application. But now I a stuck with how can I add integration test towards the newly deployed lambda version in the preHook handler. 
I am using "AllAtOnce" canary configuration. I am looking for a way for executing test agianst the new lambda version.

My preHook handler is as follows. Please suggest...

========================================
const aws = require('aws-sdk');
const codedeploy = new aws.CodeDeploy({apiVersion: '2014-10-06'});

module.exports.pre = (event, context, callback) => {
  //Read the DeploymentId from the event payload.
  var deploymentId = event.DeploymentId;

  //Read the LifecycleEventHookExecutionId from the event payload
  var lifecycleEventHookExecutionId = event.LifecycleEventHookExecutionId;

    console.log('We are running some integration tests before we start shifting traffic...');
    console.log('DeploymentId: ' + deploymentId);
    console.log('BUT NOT SURE HOW TO RUN TEST HERE  AGAINST THE NEW VERSION!'');

  /*
   Enter validation tests here.
  */
  // Prepare the validation test results with the deploymentId and
  // the lifecycleEventHookExecutionId for AWS CodeDeploy.
  var params = {
      deploymentId: deploymentId,
      lifecycleEventHookExecutionId: lifecycleEventHookExecutionId,
      status: 'Succeeded' // status can be 'Succeeded' or 'Failed'
  };
  
  // Pass AWS CodeDeploy the prepared validation test results.
  codedeploy.putLifecycleEventHookExecutionStatus(params, function(err, data) {
      if (err) {
          // Validation failed.
          callback('Validation test failed');
      } else {
          // Validation succeeded.
          callback(null, 'Validation test succeeded');
      }
  });
};

**Comment by davidgf** [comment]
Hey @shaheer-k, you can just invoke the `$LATEST` version of your Lambda function. Even if you use `AllAtOnce`, all the traffic is being routed to the old version by the time the pre hook is executed, but you can reach the new version by using the `$LATEST` alias. Check [this blog post](https://hackernoon.com/canary-deployments-in-serverless-applications-b0f47fa9b409) I wrote if you want to know more details about how CodeDeploy works.
