### ISSUE TITLE
New CodeDeploy Deployment Group and Deployment are created for each lambda function

### ISSUE THREAD

**Issue by apedzko** [davidgf/serverless-plugin-canary-deployments#73]
Hi!

I'm trying to test the plugin on serverless.yml containing 2 lambda functions and i can see 2 CodeDeploy deployment groups and 2 deployments created when i run the "serverless deploy" command. 

I'm not sure that it will work correctly with my production project which contains 20+ lambda functions. I believe it might hit the resource limit for the CloudFormation template.

Is there any way to start a single CodeDeploy deployment with pre and post hooks, execute some tests from the hooks and rollback all the lambda functions?

**Comment by davidgf** [comment]
Hi @apedzko, unfortunately that cannot be solved immediately. I always had in mind trying to create all the deployment resources in a nested stack (which I haven't yet checked whether it's possible), but I didn't have any time to implement it. PRs are welcome :sweat_smile:
