### ISSUE TITLE
Support for ALB event source?

### ISSUE THREAD

**Issue by ReddytoRumble** [davidgf/serverless-plugin-canary-deployments#77]
Sorry if this isn't in the appropriate format of a typical issue. I'm considering the use of this plugin to orchestrate canary deployments with my lambda functions. The [supported event sources](https://github.com/davidgf/serverless-plugin-canary-deployments#limitations) don't list the ALB event source as one of them. Is it accurate to say that this plugin doesn't support this event source yet? If yes,  I'm open to contributing a PR that could potentially address this.

Any help would be appreciated 🙏. Thank you

**Comment by davidgf** [comment]
Hi there! First of all, I'm very sorry for the delay, it's been quite busy at work lately. It means exactly what you're describing, and your PR is welcome :smile:
