### ISSUE TITLE
DeploymentConfig should not have a hardcoded prefix CodeDeployDefault.Lambda

### ISSUE THREAD

**Issue by debae** [davidgf/serverless-plugin-canary-deployments#78]
Within deploymentSettings we can configure a type and have to choose one of the predifined types listed here https://github.com/davidgf/serverless-plugin-canary-deployments#configuration . 
At this moment we have a security policy that defines we can only use / modify resources that are prefixed with our team name. Since the type you fill in is prepended with CodeDeployDefault.Lambda hardcoded here https://github.com/davidgf/serverless-plugin-canary-deployments/blob/master/lib/CfTemplateGenerators/CodeDeploy.js#L29 we are blocked.

What are the steps to reproduce this issue?
-------------------------------------------
1. Configure a type that is created yourself, for example

```
    deploymentSettings:
      type: OurTeam-Linear10PercentEvery1Minute
```

What happens?
-------------
We get an error stating that the deploymentConfig with name CodeDeployDefault.LambdaOurTeam-Linear10PercentEvery1Minute does not exist.

What were you expecting to happen?
----------------------------------
It should not prefix with CodeDeployDefault.Lambda by default. The quickfix could be to update the documentation and mention the types with the prefix CodeDeployDefault.Lambda and then it will also support custom DeploymentConfigs.
That change however will not be backwards compatible, so I propose we create a new property **DeploymentConfigPrefix** which has a default value of CodeDeployDefault.Lambda but can be overridden to an empty value.

What versions of software are you using?
----------------------------------------
serverless-plugin-canary-deployments : 0.4.8

**Comment by davidgf** [comment]
Hi there, first of all thank you for your feedback! I definitely understand that using custom deployment configurations could be useful in some occasions, using the default ones covers the majority of the use cases. Unfortunately, my professional commitments are keeping me quite busy and I cannot work on a fix for your issue at the moment, but I encourage you to fork the project and adapt it to your needs.
Also, it's worth noting that the plugin doesn't define any custom deployment config, but rather relies on [AWS' built-in configurations](https://docs.aws.amazon.com/codedeploy/latest/userguide/deployment-configurations.html#deployment-configurations-predefined-lambda).

**Comment by debae** [comment]
In case you are open for changes regarding this bug, I've created a PR to resolved this and added an optional prefix parameter ( documentation is updated as well ) : https://github.com/davidgf/serverless-plugin-canary-deployments/pull/79

**Comment by debae** [comment]
@davidgf Is it possible to have a look at the pull request ? If possible we would like to use this official version at our company instead of the forked one.
