### ISSUE TITLE
No CodeDeploy Application or Deployment created

### ISSUE THREAD

**Issue by lovefamilychildrenhappiness** [davidgf/serverless-plugin-canary-deployments#80]
What are the steps to reproduce this issue?
-------------------------------------------

I literally cloned the example app: https://github.com/davidgf/sls-canary-example
Created a new origin and pushed the code to the new origin. I simply changed the runtime version from nodejs6.10 to nodejs12.x. Then ran the deploy:

SLS_DEBUG=1 sls deploy --verbose --stage dev --region us-east-2

What happens?
-------------

The stack successfully deployed to CloudFormation. I noticed it created a CodeDeployServiceRole. But it did not create a CodeDeploy Application or Deployment. I expected to see a CodeDeploy deployment so I could see the lambdas deployed and the traffic migrated. Why don't I see a CodeDeploy application and group from this plugin?

**Comment by davidgf** [comment]
If you deployed the service only once, this is, there is only one version of the function, there's no other function to divert traffic to, you need to have at least two of them. As stated in the README of the example:

> To check how traffic is shifted gradually, modify handler.js and deploy your service again. You'll see that the output varies across endpoint calls.
