### ISSUE TITLE
Using type AllAtOnce to skip alarms checking

### ISSUE THREAD

**Issue by kdybicz** [davidgf/serverless-plugin-canary-deployments#82]
What are the steps to reproduce this issue?
-------------------------------------------
1. I've SLS setup to deploy Lambda with deployment type `Canary10Percent5Minutes`, while monitoring three Alerts.
2. Sometimes I need to deploy ASAP regardless of the status of the Alerts, so I thought that using deployment type `AllAtOnce` would fit here

What happens?
-------------

`AllAtOnce` doesn't prevent deployment to fail if any of Alerts is triggered.

What were you expecting to happen?
----------------------------------

I expected that only the validation hooks would be taken into consideration while deploying with type `AllAtOnce`:
`AllAtOnce: shifts all the traffic to the new version, useful when you only need to execute the validation hooks.`

Any logs, error output, etc?
----------------------------
...

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
    "serverless": "^1.66.0",
    "serverless-offline": "^5.12.1",
    "serverless-plugin-canary-deployments": "^0.4.8"

**Comment by davidgf** [comment]
Hi there. I'm very sorry, but if you add some alarms to the deployment settings and any of them is triggered, CodeDeploy will cancel the deployment. If you don't want to take those alerts into consideration, just remove the alarms from the deployment settings in your serverless.yml

**Comment by kdybicz** [comment]
There is no word about alerts in the documentation. IMO in that case you should update documentation or change implementation 🤔 

> **AllAtOnce**: shifts all the traffic to the new version, useful when you **only need to execute the validation hooks**.
